USE [master]
GO
/****** Object:  Database [minimal_api]    Script Date: 16/10/2024 08:45:18 ******/
CREATE DATABASE [minimal_api]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'minimal_api', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\minimal_api.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'minimal_api_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\minimal_api_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [minimal_api] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [minimal_api].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [minimal_api] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [minimal_api] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [minimal_api] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [minimal_api] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [minimal_api] SET ARITHABORT OFF 
GO
ALTER DATABASE [minimal_api] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [minimal_api] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [minimal_api] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [minimal_api] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [minimal_api] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [minimal_api] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [minimal_api] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [minimal_api] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [minimal_api] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [minimal_api] SET  ENABLE_BROKER 
GO
ALTER DATABASE [minimal_api] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [minimal_api] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [minimal_api] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [minimal_api] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [minimal_api] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [minimal_api] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [minimal_api] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [minimal_api] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [minimal_api] SET  MULTI_USER 
GO
ALTER DATABASE [minimal_api] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [minimal_api] SET DB_CHAINING OFF 
GO
ALTER DATABASE [minimal_api] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [minimal_api] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [minimal_api] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [minimal_api] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [minimal_api] SET QUERY_STORE = ON
GO
ALTER DATABASE [minimal_api] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [minimal_api]
GO
/****** Object:  Table [dbo].[Administradores]    Script Date: 16/10/2024 08:45:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Administradores](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[Perfil] [nvarchar](10) NOT NULL,
	[Senha] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 16/10/2024 08:45:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[Senha] [nvarchar](50) NOT NULL,
	[Perfil] [nvarchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Veiculos]    Script Date: 16/10/2024 08:45:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Veiculos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](150) NOT NULL,
	[Marca] [nvarchar](100) NOT NULL,
	[Ano] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [minimal_api] SET  READ_WRITE 
GO
